import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#36B0F0",
    alignItems: "center",
    justifyContent: "center",
  },
  avatar: {
    width: "40%",
    height: "20%",
    margin: "3%",
  },
  input: {
    backgroundColor: "#C5F1E7",
    width: "80%",
    height: 50,
    margin: "3%",
    padding: 5,
    borderRadius: 8,
    textAlign: "center",
    fontSize: 20,
  },
  pressable: {
    backgroundColor: "#F15656",
    width: "65%",
    height: 70,
    alignItems: "center",
    justifyContent: "center",
    marginTop: "3%",
    marginBottom: "3%",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowColor: "#9A5252",
    shadowOpacity: 0.8,
    shadowRadius: 2,
    inner: true,
  },
  startText: {
    marginTop: "10%",
    fontSize: 15,
    color: "#fff",
  },
  body: {
    flex: 1,
    flexDirection: "row",
    // backgroundColor: "#60A5FA",
  },
  leftView: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    width: "50%",
    margin: "2%",
  },
  rightView: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    width: "50%",
    margin: "2%",
  },
  card: {
    width: "100%",
    height: "15.6%",
    margin: "2%",
    alignItems: "center",
    justifyContent: "center",
    opacity: 0.75,
  },
  img: {
    width: "50%",
    height: "80%",
    margin: 5,
  },
  cardText: {
    width: "100%",
    height: "100%",
    borderRadius: 20,
    textAlign: "center",
    textAlignVertical: "center",
    fontSize: 25,
    fontWeight: "bold",
    backgroundColor: "#7f5Eff",
  },
  cardImg: {
    width: "100%",
    height: "100%",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#8D3Eff",
  },
  topBar: {
    flex: 1 / 15,
    backgroundColor: "#1E3A8A",
    justifyContent: "center",
    padding: 8,
  },
});
